version: "3.1"

services: 
  web:
    build: .
    container_name: react_hooks
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports: 
      - 8080:8080
      - 3000:3000
    environment:
      - COMMAND=${COMMAND}