version: "3.1"

services: 
  web:
    build: .
    container_name: react_hooks
    volumes:
      - .:/home/app
    ports: 
      - 8080:8080
      - 8001:3000
    environment:
      - COMMAND=${COMMAND}